### ISSUE TITLE
KTProcessorToolbox async Run

### ISSUE THREAD

**Issue by laroque** [project8/nymph#10]
To make python-based running useful, we want to be able to configure a processing pipeline, but give the user interactive access to the data at various points during the processing. Based on discussion with Noah, the current plan involves the following changes. Obviously this may need to adapt as we see how things look in practice.

- [x] Alter KTProcessorToolbox::Run() to be a non-blocking call (or add a parallel method which is non-blocking if that's easier to not break existing executables)
- [x] Modify the Signal/Slot system to allow some connections to also be "break points" during processing. The user will be able to access the KTData object being provided in the signal prior to it being passed to the slot of the next processor.
- [x] Add a KTProcessorToolbox::JoinGetData() method (possibly with a different name etc.) which is a blocking call. It should block until a break point is reached, the return the data object so that a user can work with it interactively.
- [x] Add a KTProcessorToolbox::Resume() (maybe different name, maybe is actually still just Run()?) which continues from the break point until processing completes or another break is reached.

**Comment by nsoblath** [comment]
This is essentially done as of commit c80e9b9dacebb7a08bd5d7a45713a3612fd0b1cc
