### ISSUE TITLE
Nymph does not build with ROOT dependence

### ISSUE THREAD

**Issue by evzayas** [project8/nymph#4]
Even with the option `Katydid_USE_ROOT` turned on in the cmake build, this option does not propagate to Nymph appropriately.

Take as an example the config file [Katydid/DisplayFFT.json](https://github.com/project8/katydid/blob/develop/Examples/ConfigFiles/DisplayFFT.json), which at the top flags the variable `root-app`. This should start a TApplication in line 198 of [nymph/KTApplication.cc ](https://github.com/project8/nymph/blob/4df2fc37f84d3c70de2e0377f7c1f05efb6a941f/Library/Application/KTApplication.cc), but without ROOT it instead produces a warning, at line 200:

```TApplication requested, but Nymph has been built without ROOT dependence.```

Consequently the display window cannot generate, as the ROOT gClient is not found:

```Unable to find the ROOT gClient; Did you start a TApplication?```

I have implemented a fix to this on my local repo, by copying the relevant lines in Katydid/CMakeLists.txt to nymph/CMakeLists.txt as well. We should discuss the most appropriate way to fix this for the longer term.

**Comment by nsoblath** [comment]
I'll create a subclass of KTApplication in Katydid that has the ROOT dependence.  ROOT will be stripped out of Nymph::KTApplication.  Nymph::KTApplication may need to be refactored a bit.  The main content of Katydid.cc will need to be moved into a function that can be passed a KTApplication pointer.

**Comment by nsoblath** [comment]
@evzayas: I've implemented a fix in Katydid branch feature/nymphrootisolation.  Can you please test it out?  Be sure to do a `git submodule update` because Nymph has been updated as well.  The current Katydid commit is 55f6e98.

**Comment by evzayas** [comment]
Quick test of this earlier today seems good! The display window boots up and behaves just as it did after I altered the CMakeLists file on my copy.

**Comment by nsoblath** [comment]
Great.  I will merge this into develop, then.
